-
  name: playbook-deploy-appv2
  hosts: target1
  tasks:

    - name: update package sources
      command: apt update

    - name: install packets
      command: apt install -y docker docker-ce docker-ce-cli containerd.io docker-compose


    - name: deploy using docker-compose
      docker_compose:
           project_name: todo-mysqlv2
           definition:
                version: "2.0"
                services:
                   app:
                        image: rubenbaraja1/getting-started
                        ports:
                          - "{{http_port}}"
                        environment:
                          MYSQL_HOST: mysql
                          MYSQL_USER: root
                          MYSQL_PASSWORD: l!k3@b05ch
                          MYSQL_DB: todos
                        depends_on:
                           - mysql

                   mysql:
                        image: mysql:5.7
                        volumes:
                          - todo-mysql-data:/var/lib/mysql
                        environment:
                          MYSQL_ROOT_PASSWORD: l!k3@b05ch
                          MYSQL_DATABASE: todos

                volumes:
                     todo-mysql-data:
